name: feature-auto-update
on:
  push:
    branches: [develop]
  schedule:
    - cron: "17 6 * * *" # daily at 06:17 UTC
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: feature-auto-update
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            const prs = await github.paginate(github.rest.pulls.list, { owner, repo, state: 'open', base: 'develop', per_page: 100 });
            const candidates = prs.filter(pr => pr.head.ref.startsWith('feature/') && pr.head.repo.full_name === `${owner}/${repo}`);

            for (const pr of candidates) {
              // Get details (mergeable_state can be 'behind')
              const { data } = await github.rest.pulls.get({ owner, repo, pull_number: pr.number });
              if (data.mergeable_state === 'behind') {
                try {
                  await github.rest.pulls.updateBranch({
                    owner, repo, pull_number: pr.number,
                    expected_head_sha: data.head.sha
                  });
                  core.info(`PR #${pr.number} updated (develop -> ${data.head.ref}).`);
                } catch (e) {
                  core.info(`Update PR #${pr.number} not possible: ${e.status} ${e.message}`);
                }
              }
            }
